
version: "3.9"

services:
  database:
    image: postgres
    container_name: database_moovin_challenge
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_USER=moovin
      - POSTGRES_PASSWORD=1234
      
    volumes:
      - data:/data/postgres
      
volumes:
  data:
    driver: local
